/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;
import domain.Task;
import domain.TaskGroup;
import domain.TaskStatus;
import domain.TaskType;
import java.awt.event.ActionListener;
import java.net.SocketException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.coordinator.ViewCordinator;
import view.form.components.table.TaskTableModel;
import view.form.mode.FrmMode;

/**
 *
 * @author FON
 */
public class FrmTask extends javax.swing.JDialog {

    /**
     * Creates new form FrmAddTask
     */
    public FrmTask(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTitle2 = new javax.swing.JTextField();
        txtDeadline2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescription2 = new javax.swing.JTextArea();
        cbPriority2 = new javax.swing.JComboBox<>();
        btnAddTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFinishDate = new javax.swing.JTextField();
        btnDeleteTask = new javax.swing.JButton();
        btnUpdateTask = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Task"));

        jLabel11.setText("Title:");

        jLabel12.setText("Deadline:");

        jLabel13.setText("Description:");

        jLabel14.setText("Priority:");

        txtDescription2.setColumns(20);
        txtDescription2.setRows(5);
        jScrollPane4.setViewportView(txtDescription2);

        btnAddTask.setText("Add");

        jLabel1.setText("Status:");

        jLabel2.setText("Start date:");

        jLabel15.setText("Finish date:");

        btnDeleteTask.setText("Delete");

        btnUpdateTask.setText("Update");

        jLabel3.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(64, 64, 64)
                                .addComponent(txtFinishDate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnDeleteTask)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateTask)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddTask))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeadline2)
                                    .addComponent(txtTitle2)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(cbPriority2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStartDate)
                                    .addComponent(txtID))))
                        .addGap(58, 58, 58))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDeadline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPriority2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFinishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTask)
                    .addComponent(btnDeleteTask)
                    .addComponent(btnUpdateTask))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnUpdateTask;
    private javax.swing.JComboBox<Object> cbPriority2;
    private javax.swing.JComboBox<Object> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtDeadline2;
    private javax.swing.JTextArea txtDescription2;
    private javax.swing.JTextField txtFinishDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTitle2;
    // End of variables declaration//GEN-END:variables

   

    public void addBtnAddTaskListener(ActionListener actionListener) {
        btnAddTask.addActionListener(actionListener);
    }

    public void addBtnUpdateTaskListener(ActionListener actionListener) {
        btnUpdateTask.addActionListener(actionListener);
    }

    public void addBtnDeleteTaskListener(ActionListener actionListener) {
        btnDeleteTask.addActionListener(actionListener);
    }

   

    public JButton getBtnAddTask() {
        return btnAddTask;
    }

    public JButton getBtnDeleteTask() {
        return btnDeleteTask;
    }

    public JButton getBtnUpdateTask() {
        return btnUpdateTask;
    }

    public JComboBox<Object> getCbPriority2() {
        return cbPriority2;
    }

    public JComboBox<Object> getCbStatus() {
        return cbStatus;
    }

    public JTextField getTxtDeadline2() {
        return txtDeadline2;
    }

    public JTextArea getTxtDescription2() {
        return txtDescription2;
    }

    public JTextField getTxtFinishDate() {
        return txtFinishDate;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtStartDate() {
        return txtStartDate;
    }

    public JTextField getTxtTitle2() {
        return txtTitle2;
    }

    

    public void setBtnAddTask(JButton btnAddTask) {
        this.btnAddTask = btnAddTask;
    }

    public void setBtnDeleteTask(JButton btnDeleteTask) {
        this.btnDeleteTask = btnDeleteTask;
    }

    public void setBtnUpdateTask(JButton btnUpdateTask) {
        this.btnUpdateTask = btnUpdateTask;
    }

    public void setCbPriority2(JComboBox<Object> cbPriority2) {
        this.cbPriority2 = cbPriority2;
    }

    public void setCbStatus(JComboBox<Object> cbStatus) {
        this.cbStatus = cbStatus;
    }

    public void setTxtDeadline2(JTextField txtDeadline2) {
        this.txtDeadline2 = txtDeadline2;
    }

    public void setTxtDescription2(JTextArea txtDescription2) {
        this.txtDescription2 = txtDescription2;
    }

    public void setTxtFinishDate(JTextField txtFinishDate) {
        this.txtFinishDate = txtFinishDate;
    }

    public void setTxtID(JTextField txtID) {
        this.txtID = txtID;
    }

    public void setTxtStartDate(JTextField txtStartDate) {
        this.txtStartDate = txtStartDate;
    }

    public void setTxtTitle2(JTextField txtTitle2) {
        this.txtTitle2 = txtTitle2;
    }
    
    
    
}
